title: jaagastudy
description: A New Kind of School for a New Way of Living.
url: "https://haricm.github.io"
baseurl: "/jaagastudy"

navigation:
  - title: Home
    url: /
    section: home
  - title: Bootcamp
    url: /bootcamps/creative-ai-bootcamp/01.html
    section: bootcamp
  - title: Blog
    url: /blog.html
    section: blog
  - title: Join Discord
    url: "https://discord.gg/ZtakuZXEF"
    external: true
    class: discord-btn

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      section: blog

permalink: /blog/:title.html
